version: 2
jobs:
  build:
    machine: true
    - setup_remote_docker:
      docker_layer_caching: true
    steps:
      - checkout
      - run: |
          docker build -t platzi .
  test:
    machine: true
    - setup_remote_docker:
      docker_layer_caching: true
    steps:
      - checkout
      - run: |
          docker run platzi npm test
  deploy:
      machine: true
      - setup_remote_docker:
        docker_layer_caching: true
      steps:
        - run:
            name: Deploy with Now
            command: 
              - sh deployments/qa.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
  build-deploy:
      jobs:
        - build
        - deploy:
            requires:
              - build
            filters:
              branches:
                only: /feature_*/


# must be named circle.yml and must be at the root of project
# version 1
# machine:
#   services:
#     - docker

# dependencies:
#   override:
#     - docker build -t platzi

# test:
#   override:
#     - docker run platzi npm test